# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.9
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1.1.6
      with:
        version: 1.1.6
        virtualenvs-create: false
        virtualenvs-in-project: false
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        export PYTHONPATH=src
        poetry run pytest
